### ISSUE TITLE
Crashed under Fritz GUI after Engine-Install

### ISSUE THREAD

**Issue by Gravitar64** [joergoster/Stockfish-NNUE#3]
Hi,

I tried to install you're engine under Fritz 12 GUI. Stockfish engines from development works fine. But you're engine (sf-nnue run (halfkp-256x2-32-32) x64-popc.exe) with subfolder "eval" and the newes bin (nn.bin with 21MB) crashes after starting analysis.

**Comment by joergoster** [comment]
Maybe you better try Norman's compiles: https://github.com/FireFather/sf-nnue/releases

**Comment by Gravitar64** [comment]
OK, I tried the Norman compiles (popc for my system) and it crashed again and again. But when I create an engine under fritz and AFTER creating it, changed the path for the EvalFile to "eval\nn.bin", than it works.

If i change this path when create the engine, the engine crashed. Strange behavieour but so it worked.
