### ISSUE TITLE
nnue-learn problem

### ISSUE THREAD

**Issue by amchess** [joergoster/Stockfish-NNUE#4]
I tried to build this target with MinGW and the following command:
mingw32-make nnue-learn ARCH=x86-64-bmi2 COMP=mingw CXX=x86_64-w64-mingw32-g++ -j %Number_Of_Processors%

Before it asked cblas.h library and I added it.
After there is the following error (and some others after):
In file included from C:/MinGW/mingw64/lib/gcc/x86_64-w64-mingw32/8.1.0/include/c++/filesystem:37,
                 from learn/learner.cpp:18:
C:/MinGW/mingw64/lib/gcc/x86_64-w64-mingw32/8.1.0/include/c++/bits/fs_path.h: In member function 'std::filesystem::__cxx11::path& std::filesystem::__cxx11::path::operator/=(const std::filesystem::__cxx11::path&)':
C:/MinGW/mingw64/lib/gcc/x86_64-w64-mingw32/8.1.0/include/c++/bits/fs_path.h:237:47: error: no match for 'operator!=' (operand types are 'std::filesystem::__cxx11::path' and 'std::filesystem::__cxx11::path')
    || (__p.has_root_name() && __p.root_name() != root_name()))

I seems a bug of 8.1.0 version for the filesystem, include.
Can you do a workaround?

**Comment by joergoster** [comment]
It compiles under msys2 with gcc-10.1 without problems.

Maybe this is of some help. (from https://en.cppreference.com/w/cpp/filesystem)

> Using this library may require additional compiler/linker options. GNU implementation prior to 9.1 requires linking with -lstdc++fs and LLVM implementation prior to LLVM 9.0 requires linking with -lc++fs

**Comment by amchess** [comment]
Not so trivial, unfortunately.
I finally was able and I tell for other people having the same problem.
In mingw 8.1.0, I wasn't able at all.
It seems a bug of this version:
[https://stackoverflow.com/questions/50546025/mingw-w64-8-1-0-rev-0-doesnt-compile-when-including-filesystem/50579971](https://stackoverflow.com/questions/50546025/mingw-w64-8-1-0-rev-0-doesnt-compile-when-including-filesystem/50579971)

Conversely, with 7.3.0, it works, but <filesystem> is <experimental/filesystem>.
Clearly, also OpenBlas library must be installed and included the corresponding headers file.
For the rest, I always used msys1.0 and MinGW, but if you ensure me msys2 is now better, I can learn to use it.
