### ISSUE TITLE
Repository integration

### ISSUE THREAD

**Issue by ghost** [joergoster/Stockfish-NNUE#9]
Dear Jörg,

I'm going to create an optimized trainer from the Nodchip branch. I also created a different chess engine from Stockfish that I need to be developed by other members:

- https://github.com/HalfKP/NNUE 
- https://github.com/HalfKP/Lifish

I greatly value you as a colleague, and I believe that we can work well together as a team in the further. Feel free to contact me if you would like to discuss this further.

Sincerely, 
Gary

**Comment by EarlyEdition** [comment]
https://github.com/EarlyEdition/Lifish/tree/YBWC

**Comment by EarlyEdition** [comment]
@joergoster Are you here?

**Comment by ghost** [comment]
@joergoster Please let me know what you think. Do you agree with this integration? 
If not, no worries. Feel free to close this issue.

**Comment by ghost** [comment]
I close this issue in the merge with [sf-nnue-aio](https://github.com/FireFather/sf-nnue-aio) repository  by @FireFather.
